---
- import_tasks: ../common/tasks/main.yaml

- name: Configuring Vlan Interfaces
  template:
    src: "{{ config_vlan_interfaces_template }}"
    dest: /etc/network/interfaces.d/vlans.cfg
    owner: root
    group: root
    mode: 0644
  become: true

- name: Configuring VxLAN Interfaces
  template:
    src: "{{ config_vxlan_interfaces_template }}"
    dest: /etc/network/interfaces.d/vxlans.cfg
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart networking

- name: Configuring VxLAN Bridge
  template:
    src: "{{ config_vxlan_bridge_template }}"
    dest: /etc/network/interfaces.d/vxlan_bridge.cfg
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart networking

- name: Make sure that networking was restarted after initial bridge config setup
  meta: flush_handlers

- name: Configuring port forwarding for VxLAN Bridge
  sysctl:
    name: "net/ipv4/conf/{{ br_vxlan }}/forwarding"
    value: 1
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: Configuring port forwarding per VLAN
  sysctl:
    name: "net/ipv4/conf/{{ initial_bond_name }}.{{ item.vlan_id }}/forwarding"
    value: 1
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
  loop: "{{ network_configuration.routers.value[inventory_hostname].vlans }}"

- name: Configuring IP forwarding for Bridge
  sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes

- name: NAT traffic
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ initial_bond_name }}"
    source: 192.168.0.0/16
    jump: MASQUERADE
  become: yes
